[default]
# APP - CONFIGURAÇÕES GERAIS
APPNAME = "TG UFABC - ENERGIA - PREVISOR"
APPNAME_LOG = "TG_UFABC_ENERGIA_PREVISOR.log"
APPNAME_TITLE = "TG UFABC - ENERGIA - PREVISOR DE GERAÇÃO DE ENERGIA"
APPNAME_TITLE_ICON = ":factory:"
LOGO_APP = "src/assets/logo_ufabc.jpg"
STYLES_CSS = 'src/styles/style.css'

# DATAFRAMES
LIST_OPTIONS_DATAFRAME_EXPLORER = ["dataframe_explorer"]
OPTION_DATAFRAME_EXPLORER = "dataframe_explorer"
NUM_MIN_CATEGORY = 50


# MAPA
MAP_ICON_DEFALT = "ok-sign"
MAP_DICT_ICON_DEFAULT = {}

[development]
LIST_DATASETS = ["GHCN", "INMET"]

# GHCN
DATA_DIR_STATIONS_GHCN = "src/data/RESULTS/dataset_ghcn_group_freq_month.xlsx"
LIST_COLUMNS_ORDER_GHCN = ['station', 'name', 'lat', 'long', 'elev', 'state', 'city', 'measurement date', 'month', 'year', 'avg_temp', 'avg_awnd', 'avg_prcp']
LIST_COLUMNS_GROUP_GHCN = ['name', 'state', 'city']
LIST_COLUMNS_ORDER_MAP_GHCN = ['station', 'name', 'lat', 'long', 'elev', 'state', 'city']
COLUMN_TIMESERIES_X_AXIS_GHCN = 'measurement date'
COLUMN_TIMESERIES_TEMP_GHCN = 'avg_temp'

# INMET
DATA_DIR_STATIONS_INMET = ""

VALIDATOR_ADD_LAYER = false # TORNANDO true, REMOVE A FEATURE DE MARKER CLUSTER
MAP_SAVE_FIGURE = true
MAP_LAYER_DEFAULT = "cartodbpositron"
MAP_SAVE_NAME = "PLOT_MAP_STATIONS.html"
VALIDATOR_MARKER_CLUSTER = true
COLUMN_MARKER_CLUSTER = "state"

# PARÂMETROS USADOS NA SELEÇÃO DO MAPA
COLUMN_STATUS = ""
COLUMN_LATITUDE = "lat"
COLUMN_LONGITUDE = "long"
MAP_COLUMN_TOOLTIP = "name"
MAP_COLUMN_HEADER = "name"