[default]
# APP - CONFIGURAÇÕES GERAIS
APPNAME = "TG UFABC - ENERGIA - PREVISOR"
APPNAME_LOG = "TG_UFABC_ENERGIA_PREVISOR.log"
APPNAME_TITLE = "TG UFABC - ENERGIA - PREVISOR DE GERAÇÃO DE ENERGIA"
APPNAME_TITLE_ICON = ":factory:"
LOGO_APP = "src/assets/logo_ufabc.png"
STYLES_CSS = 'src/styles/style.css'

# DATAFRAMES
LIST_OPTIONS_DATAFRAME_EXPLORER = ["dataframe_explorer"]
OPTION_DATAFRAME_EXPLORER = "dataframe_explorer"
NUM_MIN_CATEGORY = 9999


# MAPA
MAP_ICON_DEFALT = "ok-sign"
MAP_DICT_ICON_DEFAULT = {}

[development]
LIST_DATASETS = ["GHCN", "INMET"]

# GHCN
DATA_DIR_STATIONS_GHCN = "src/data/4_RESULTS_DATASET_GHCN_DAILY/DATASET_GHCN_PROCESING_FREQ_DAILY_UNIQUE_STATION.csv"
LIST_COLUMNS_ORDER_GHCN = ['measurement date', 'day', 'month', 'year', 'name', 'lat', 'lon', 'state', 'city', 'temp', 'prcp', 'wdsp']
LIST_COLUMNS_GROUP_GHCN = ['name', 'state', 'city']
LIST_COLUMNS_ORDER_MAP_GHCN = ['name', 'state', 'city', 'lat', 'lon']
COLUMN_TIMESERIES_X_AXIS_GHCN = 'measurement date'
COLUMN_TIMESERIES_TEMP_GHCN = 'temp'
COLUMN_TIMESERIES_PRCP_GHCN = 'prcp'
COLUMN_TIMESERIES_WDSP_GHCN = 'wdsp'

# INMET
DATA_DIR_STATIONS_INMET = ""

VALIDATOR_ADD_LAYER = false # TORNANDO true, REMOVE A FEATURE DE MARKER CLUSTER
MAP_SAVE_FIGURE = false # TORNANDO true, SALVA UM HTML DO FOLIUM MAP
MAP_LAYER_DEFAULT = "cartodbpositron"
MAP_SAVE_NAME = "PLOT_MAP_STATIONS.html"
VALIDATOR_MARKER_CLUSTER = true
COLUMN_MARKER_CLUSTER = "state"

# PARÂMETROS USADOS NA SELEÇÃO DO MAPA
COLUMN_STATUS = ""
COLUMN_LATITUDE = "lat"
COLUMN_LONGITUDE = "lon"
MAP_COLUMN_TOOLTIP = "name"
MAP_COLUMN_HEADER = "name"